AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-playground

  Sample SAM Template for lambda-playground
  
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: hello-world/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints: 
        - app.ts
  ReceptionistFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: receptionist/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        HelloWorld:
          Type: SQS # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#sqs
          Properties:
            Queue: !GetAtt PersonJoinedQueue.Arn
            BatchSize: 1
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
  LastReceivedPersonFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: last-received-person/
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        LastReceivedPerson:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /last-received-person
            Method: get
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
  PersonJoinedQueue:
    Type: AWS::SQS::Queue
  AudienceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: Audience
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
  PeopleReceivedTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: PeopleReceived
      KeySchema:
        - AttributeName: Room
          KeyType: HASH
        - AttributeName: ReceivedAt
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: Room
          AttributeType: S
        - AttributeName: ReceivedAt
          AttributeType: S
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello"
  HelloWorldApiLocal:
    Description: "Localstack API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.localhost.localstack.cloud:4566/Prod/hello"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
  ReceptionistFunction:
    Description: "Receptionist Lambda Function ARN"
    Value: !GetAtt ReceptionistFunction.Arn
  ReceptionistFunctionIamRole:
    Description: "Implicit IAM Role created for Receptionist function"
    Value: !GetAtt ReceptionistFunctionRole.Arn
  LastReceivedPersonApi:
    Description: "API Gateway endpoint URL for Prod stage for LastReceivedPerson function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/last-person-received"
  LastReceivedPersonApiLocal:
    Description: "Localstack API Gateway endpoint URL for Prod stage for LastReceivedPerson function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.localhost.localstack.cloud:4566/Prod/last-person-received"
  LastReceivedPersonFunction:
    Description: "LastReceivedPerson Lambda Function ARN"
    Value: !GetAtt LastReceivedPersonFunction.Arn
  LastReceivedPersonFunctionIamRole:
    Description: "Implicit IAM Role created for LastReceivedPerson function"
    Value: !GetAtt LastReceivedPersonFunctionRole.Arn
  PersonJoinedQueue:
    Description: "PersonJoinedQueue SQS Queue ARN"
    Value: !GetAtt PersonJoinedQueue.Arn
