name: Lambda Playground Pipeline
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Setup AWS SAM cli
        uses: aws-actions/setup-sam@v2
      - name: Setup Localstack (and AWS wrappers)
        run: |
          docker pull localstack/localstack
          pip install localstack==0.14.3.3
          pip install awscli-local[ver1]
          pip install aws-sam-cli-local
      - name: Check out source code
        uses: actions/checkout@v3
      - name: Run Unit and Integration Tests
        run: ./scripts/test.sh
      - name: Run Acceptance Tests
        run: ./scripts/acceptance.sh
      - run: echo "🍏 This job's status is ${{ job.status }}."
